### ISSUE TITLE
Unknown zk LSP command: zk.link

### ISSUE THREAD

**Issue by Bekaboo** [mickael-menu/zk-nvim#101]
Hi, I just discovered this plugin a few days ago and I love it! Thanks for your hard work on this plugin!

Everything works as expected except that when I execute the command `ZkInsertLink` or `ZkInsertLinkAtSelection` I get this error message:

```
Error executing vim.schedule lua callback: RPC[Error] code_name = InvalidRequest, message = "unknown zk LSP command: zk.link"
```

Here is my config for zk.nvim:

```lua
vim.env.ZK_NOTEBOOK_DIR= os.getenv('HOME') .. '/Notes'

require('zk').setup({
  picker = 'telescope',
})
```

and here is the info shown in `:LspInfo`

```lua
 Client: zk (id: 1, bufnr: [35, 8])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             zk lsp
 
 Client: zk (id: 2, bufnr: [35, 8])
 	filetypes:       markdown
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             zk lsp
```

Is there something is missing in my config? How can fix this problem?

**Comment by mickael-menu** [comment]
It's a new feature that requires zk 0.13.0, which I released a minute ago: https://github.com/mickael-menu/zk/releases/tag/v0.13.0
It might not be available on your package managers yet.
