### ISSUE TITLE
Only ZkNew and ZkIndex commands available

### ISSUE THREAD

**Issue by Joelius300** [mickael-menu/zk-nvim#106]
Disclaimer: I'm still at the beginning of this journey and have very little experience with zk and neovim.

After installing zk via the package manager and installing zk-nvim via AstroNvim's packer-like way, I can see the lsp attach to one of my notes inside an initialized Zettelkasten (see :LspInfo output below). However, when I try to invoke :ZkNotes, I find that only :ZkNew and :ZkIndex exist.

![LspInfo](https://user-images.githubusercontent.com/52202086/219776399-096f7714-f5ec-4b56-ad06-611ed5f10e8f.png)

(typed `:Zk` and pressed tab)

![image](https://user-images.githubusercontent.com/52202086/219776594-3a0ff84d-7172-467d-924d-d0656013fc5d.png)

Any idea what I am doing wrong? 😅 

To install and setup the plugin, I have the following code in my `user/init.lua` file for the user specific configuration within AstroNvim.

```lua
plugins = {
  init = {
    "mickael-menu/zk-nvim",
  },
  ["zk"] = {
    picker = "telescope",
  },
},
lsp = {
  servers = {
    "zk",
  },
},
```

From my understanding, this should be equivalent to

(just packer)

```lua
use("mickael-menu/zk-nvim")
```

(setup)

```lua
require("zk").setup({ picker = "telescope" })
```

the additional `servers` entry is required because AstroNvim is using [mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim) behind the scenes and wouldn't recognize zk otherwise.

**Comment by UnkwUsr** [comment]
Very strange, but looks like you use very old version of the plugin (like at commit 89179f1) where only `:ZkIndex` and `:ZkNew` commands presented yet.

Can you find local folder with installed plugin and check file `lua/zk/commands/builtin.lua`? (if your version is really very old as I expect, then you'll not even have that file yet)

**Comment by Joelius300** [comment]
@dzintars thanks for the comment, I'll look into it when I better understand what's going on here.

@UnkwUsr thanks for the comment. I found `lua/zk/commands/builtin.lua` under `~/.local/share/nvim/site/pack/packer/start/zk-nvim` on my Manjaro system. It contains multiple calls to `commands.add` with the first two being "ZkIndex" and "ZkNew", followed by the for me nonexistent "ZkNewFromTitleSelection". I compared it with https://github.com/mickael-menu/zk-nvim/blob/main/lua/zk/commands/builtin.lua and it seems to be the same code.

**Comment by dzintars** [comment]
Mby old LSP? I mean old `zk`?

**Comment by Joelius300** [comment]
I'll confirm in a sec but I'm almost certain it's on version 12, maybe even already on 13, but not lower.

**Comment by UnkwUsr** [comment]
Try a minimal config: create file (for example, `min.lua`) with following content:

```lua
-- P.S. stealed from gitsigns:
-- https://github.com/lewis6991/gitsigns.nvim/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml

vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  zk = 'https://github.com/mickael-menu/zk-nvim',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require("zk").setup({
    picker = "telescope",
})
```
And run `nvim --clean -u min.lua`. Do you have all the `:Zk*` commands?

**Comment by Joelius300** [comment]
@UnkwUsr Yes I do!

**Comment by UnkwUsr** [comment]
Yes, there can be conflict somewhere. Try to reproduce with clean AstroNvim, and if it does, then create issue there.

**Comment by Joelius300** [comment]
Delighted to report that the major update of AstroNvim (3.10.0 right now) has solved this issue for me :)
