### ISSUE TITLE
Support for, or how to go about replicating zk with fzf-lua instead of fzf.vim/fzf proper

### ISSUE THREAD

**Issue by megalithic** [mickael-menu/zk-nvim#108]
I'm presently working with `fzf-lua` instead of `fzf/fzf.vim` and would love to replicate the basic functionality around zk's built in fzf picker behaviours and use fzf-lua instead. Was wondering if any zk users would chime in if they've done something similar.

**Comment by UnkwUsr** [comment]
Simillar: https://github.com/mickael-menu/zk-nvim/issues/28
