### ISSUE TITLE
Error during insertion of links

### ISSUE THREAD

**Issue by grimmjulian** [mickael-menu/zk-nvim#110]
Hello,

I tried installing zk and zk-nvim. I could add new Notes, but cannot insert links. ZkInsertLink as well as ZkInsertLinkAtSelection give the following error:
```
Error executing vim.schedule lua
 callback: RPC[Error] code_name = InvalidRequest, message = "unknown zk LSP command: zk.link"

```

Do you have an idea what I did wrong or how it can be fixed?

**Comment by UnkwUsr** [comment]
I think this command should be executed from file inside zk notebook (by this I mean folder where `zk init` was executed). UPD: moreover, the file should have .md extension.

**Comment by UnkwUsr** [comment]
Show `zk --version` please. Looks like you use not latest (0.13.0) [zk](https://github.com/mickael-menu/zk/) version

**Comment by grimmjulian** [comment]
I installed it via pacman, but there still is version 0.12.0. Yay has the same version.

I get an error when building from scratch, but I added the issue [https://github.com/mickael-menu/zk/issues/295](here).

I will close this issue till this works.

**Comment by UnkwUsr** [comment]
> I installed it via pacman, but there still is version 0.12.0.

Pacman updated zk to version 0.13.0 since 2023-02-20: https://archlinux.org/packages/community/x86_64/zk/

Have you run `sudo pacman -Sy`? If yes, then maybe there is some problems with [mirrors](https://wiki.archlinux.org/title/Mirror).
