### ISSUE TITLE
Typo: nvim_add_user_command

### ISSUE THREAD

**Issue by ateoi** [mickael-menu/zk-nvim#114]
The correct name is `nvim_create_user_command` <https://neovim.io/doc/user/api.html#api-command>

https://github.com/mickael-menu/zk-nvim/blob/50fc25b88fb28829ec7f5e5a4d4b458fca21a550/lua/zk/commands/init.lua#L10

**Comment by mickael-menu** [comment]
It looks like the name changed in a more recent version of Nvim. Do you want to open a PR to fix the issue?
