### ISSUE TITLE
Link incorrectly formated after completion

### ISSUE THREAD

**Issue by lcmen** [mickael-menu/zk-nvim#124]
Hello!
I'm using `nvim-lspconfig` for LSP without any auto complete plugins. When I type `[[` and use `v:lua.vim.lsp.omnifunc` (LSP completion as `omnifunc`), then characters that triggered autocompletion (`[[`) are not removed upon selection.

Is there a way to remove `[[` after inserting a link?

```
# actual text after completion:
[[[Untitled](abc)]]

# expected:
[Untitled](abc)
```

Thanks for any help!

**Comment by eric-hansen** [comment]
I believe the expected behavior is for that to be the case though.  ZK is a Wiki-style notetaking system similar to Roam, Logseq, etc... (I would call them backlinks but not sure if that would be appropriate in this context).

So I guess my question is why use `[[` when you are trying to use a normal Markdown link/reference?

**Comment by lcmen** [comment]
@eric-hansen how can I change a character that is used for autocomplete? Without typing `[[`, I'm not able to get notes from `omnifunc` completion.

**Comment by eric-hansen** [comment]
I'm an LSP user myself so I can't answer how to make that happen.  But, also, for ZK the use of `[[...]]` is what links different notes/documents together, as expected.

So essentially are you looking for a Markdown tool or a notetaking tool?

ZK is a notetaking tool with Markdown-supported syntax.  But if you're trying to reference other notes then you should use the backlink structure (`[[...]]`) and not the Markdown structure (`[]()`).

**Comment by lcmen** [comment]
From what I know `[]()` is also supported by zk, isn't it?

**Comment by mickael-menu** [comment]
Yes, `[[` is the trigger for both wiki links and markdown links. However, it requires LSP features not always available in the editor.

Try to modify the `use-additional-text-edits` config property (true or false, I don't remember the default value).

**Comment by lcmen** [comment]
@mickael-menu thanks for suggestion, unfortunately it doesn't work with `nvim-lspconfig` and `v:lua.vim.lsp.omnifunc`.

**Comment by lcmen** [comment]
Unfortunately, I didn't solve it.
