### ISSUE TITLE
Bug: `ZkNewFromTitleSelection` does not copy the last character correctly.

### ISSUE THREAD

**Issue by noriapi** [mickael-menu/zk-nvim#125]
If the last character in the selection is a non-ascii character, such as `あ` or `😀`, it will not be copied correctly and will appear as `�`.

Example

Selection
![selection](https://github.com/mickael-menu/zk-nvim/assets/70106808/04b28d6f-5335-4c2c-b5b3-2875bc1c1585)

New note
![new-note](https://github.com/mickael-menu/zk-nvim/assets/70106808/d02f9451-c0f3-4b7b-8530-5b86d210071f)

Replaced
![replaced](https://github.com/mickael-menu/zk-nvim/assets/70106808/074b72d8-a343-4419-9477-d49e7569f23f)

**Comment by mickael-menu** [comment]
I just released the 0.14.0 version of `zk` that might have an impact on that: https://github.com/mickael-menu/zk/releases/tag/v0.14.0

If you still have the problem, please open a new issue with more details to reproduce, following the new [bug reports template](https://github.com/mickael-menu/zk-nvim/issues/new?assignees=&labels=&projects=&template=bug_report.yml).
