### ISSUE TITLE
Link completion does not work with non-latin zettel name

### ISSUE THREAD

**Issue by ivan-volnov** [mickael-menu/zk-nvim#126]
Hi,

Thanks for the great tool!

Subj.

To reproduce: just try to create a note with non-latin name and link it to another note using `[[`.

**Comment by mickael-menu** [comment]
I just released the 0.14.0 version of `zk` that might have an impact on that: https://github.com/mickael-menu/zk/releases/tag/v0.14.0

If you still have the problem, please open a new issue with more details, following the new [bug reports template](https://github.com/mickael-menu/zk-nvim/issues/new?assignees=&labels=&projects=&template=bug_report.yml).
