### ISSUE TITLE
Support for fzf

### ISSUE THREAD

**Issue by pinpox** [mickael-menu/zk-nvim#13]
Hello, I see the examples for Telescope, but is fzf supported aswell? If not, how much work would it be to support it?

**Comment by kabouzeid** [comment]
Not yet. It's possible without too much effort. There is a code refactoring coming though, after that it will be very easy. Probably in a few days already :)

**Comment by kabouzeid** [comment]
https://github.com/mickael-menu/zk-nvim/pull/14

**Comment by kabouzeid** [comment]
This is now possible. Just set picker="fzf" in the setup function. See README.
