### ISSUE TITLE
Can't search/filter the LSP completion candidates

### ISSUE THREAD

**Issue by lazywei** [mickael-menu/zk-nvim#136]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

When typing `[[` the auto-completion is correctly triggered, but the candidates can't be searched/filtered.

For example, here is the list for my notes
![image](https://github.com/mickael-menu/zk-nvim/assets/2840571/d46afe15-981f-4790-aaf0-4c5baada3450)

But when I type `h` (or `H`), the candidates are just all gone.
![image](https://github.com/mickael-menu/zk-nvim/assets/2840571/cc5b4676-9aec-4e2b-8c66-89360764926e)

**Expected Behavior**
The list of candidates should be filtered correctly and show the `HHKB` as the candidate.

### How to reproduce?

1. In a folder of markdown notes
2. run `zk init` with the latest zk installed via `homebrew`
3. in neovim, type `[[` to trigger the auto-completion

### zk configuration

```toml
all default settings
```

### Neovim configuration

```viml
{
        "mickael-menu/zk-nvim",
        config = function()
            require("zk").setup({
                picker = "telescope",
            })
        end
    },
```
```


### Environment

```bash
zk 0.14.0
system: Darwin 22.5.0 arm64
NVIM v0.9.0-dev-2556+g2dfb51a2b-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-2dfb51a/share/nvim"

Run :checkhealth for more info
```

**Comment by tjex** [comment]
@lazywei you haven't included the lsp setup entries in your config. Look again at the readme for the full base config.
