### ISSUE TITLE
Support for `fzf-lua` picker

### ISSUE THREAD

**Issue by yujinyuz** [mickael-menu/zk-nvim#28]
Thanks for this great tool and plugin!

Would it be complicated to add [fzf-lua](https://github.com/ibhagwan/fzf-lua) as another picker?

It seems that the `fzf` picker in the documentation uses `fzf.vim`

**Comment by kabouzeid** [comment]
What would be the benefit?

**Comment by yujinyuz** [comment]
@kabouzeid Do you mean the benefits of creating `fzf-lua` picker?

Not much really. I just prefer having a consistent user experience

**Comment by kabouzeid** [comment]
How is the user experience different exactly? Personally I use telescope, so I wouldn't know :)

**Comment by yujinyuz** [comment]
I'm not sure what you mean but `fzf.vim` uses external previewers such as `bat` to preview the contents of the file while `fzf-lua` can be configured to use buffers as previewers similar to what telescope does.

So, if I just use `fzf.vim` here, it would look quite different.

For example

`fzf.vim`
<img width="720" alt="Screen Shot 2022-01-23 at 21 58 00" src="https://user-images.githubusercontent.com/10972027/150681975-a598b6bf-847f-4ab7-a424-91aec9d49c54.png">


`fzf-lua`

<img width="720" alt="Screen Shot 2022-01-23 at 21 58 29" src="https://user-images.githubusercontent.com/10972027/150681987-4bf66b71-7acf-487a-944b-978f80426705.png">

**Comment by kabouzeid** [comment]
That looks better indeed. If someone wants to implement this, have a look at `zk-nvim/lua/zk/pickers`.

**Comment by kabouzeid** [comment]
https://github.com/ibhagwan/fzf-lua/issues/57
