### ISSUE TITLE
On attach not working

### ISSUE THREAD

**Issue by danymat** [mickael-menu/zk-nvim#33]
Hello again !

I'm trying to hide diagnostics for `zk`, and I came up with this snippet:

```lua
				require("zk").setup({
					picker = "telescope",
					lsp = {
						config = {
							on_attach = function(_, buffer)
                                                                print(buffer)
								vim.diagnostic.hide(nil, buffer)
							end,
						},
					},
				})

```

However, it seems that the on_attach function is never called, as I never go into the print.
Am I missing something here ?

**Comment by kabouzeid** [comment]
I just checked. It is definitely called, but for some reason print() doesn't work here. Very weird. Maybe on_attach() is called on a background thread and print isn't supported there or something. Not sure if it's a Neovim bug, or maybe this behavior is documented somewhere.

**Comment by kabouzeid** [comment]
at that point the server probably hasn't yet sent the diagnostics. `vim.diagnostic.hide(nil, buffer)` will only hide the diagnostics that are currently displayed.

**Comment by kabouzeid** [comment]
What diagnostics are you getting anyways? I don't get any diagnostics.

You can disable diagnostics like so in your `.zk/config.toml`:
```toml
[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "none"
# Warn for dead links between notes.
dead-link = "none"
```

**Comment by danymat** [comment]
I'm using:
```
[lsp]

[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
wiki-title = "hint"
```

So that I can jump in each wiki title with `goto_next` and `goto_prev`. I wanted to disable diagnostics so I don't have the virtual text, but still have the jumping enabled, somehow it's working

**Comment by kabouzeid** [comment]
weird that `goto_next` and `goto_prev` are still working with diagnostics disabled. something seems off about this.

by the way I'd rather use the following snippet which will only disable the diagnostics that are coming from `zk`.

```lua
local zk_lsp_client = require("zk.lsp").client()
if zk_lsp_client then
  local zk_diagnostic_namespace = vim.lsp.diagnostic.get_namespace(zk_lsp_client.id)
  vim.diagnostic.disable(0, zk_diagnostic_namespace)
end
```

Or better yet, just disable virtual text for `zk` diagnostics:

```lua
local zk_lsp_client = require("zk.lsp").client()
if zk_lsp_client then
  local zk_diagnostic_namespace = vim.lsp.diagnostic.get_namespace(zk_lsp_client.id)
  vim.diagnostic.config({virtual_text = false}, zk_diagnostic_namespace)
end
```
