### ISSUE TITLE
Autocomplete links with filtering

### ISSUE THREAD

**Issue by lcmen** [mickael-menu/zk-nvim#37]
Hey!
Thank you for this awesome plugin. It works with `nvim-cmp` very well. I have just one problem with autocompletion on wiki links. When I type `[[` and list of all notes appear, I'm not able to filter it down - it automatically disappears if I type any letter.

Is there some special shortcut that can be used to filter list based on the title?

**Comment by mickael-menu** [comment]
That might be an issue with `nvim-cmp` or maybe some conflict in your Neovim config file. `zk` sends the completion items but Neovim + `nvim-cmp` handle everything UI-wise.

**Comment by lcmen** [comment]
@mickael-menu thanks! It turned out that I didn't have `note-filter-text` option set in my `config.toml` file. Once I configured it to use `"{{title}} {{path}}"` template, it all started working without any additional config on `nvim-cmp` side.

**Comment by mickael-menu** [comment]
Ha good catch. I'm moving this issue to the core `zk` repo as it might help someone else too.

By the way you don't need to set the `note-filter-text` option at all if you don't want a custom value. The default one is already `{{completion-label}} {{path}}`.
