### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by UnkwUsr** [mickael-menu/zk-nvim#39]
In Installation section:
https://github.com/mickael-menu/zk-nvim/blob/b13a191fbbfe427d1aadaf41419520c43abee141/README.md?plain=1#L16-L19

I'm sorry, but this would not work, as `"` is actually a comment in vimscript. Should be `'`.

~UPD: moreover, there should be custom branch setting:~

    Plug 'mickael-menu/zk-nvim', { 'branch': 'main' }

UPD2: latest version of vim-plug (0.11.0) have no need in custom branch setting.

**Comment by eric-hansen** [comment]
`"` is only a comment if it's the first character of the line.  In this context it's correctly the start of a string.

**Comment by eric-hansen** [comment]
I don't use vim-plug.

Are you using Vim or Neovim?

**Comment by UnkwUsr** [comment]
Neovim v0.6.1

**Comment by mickael-menu** [comment]
I tested and I indeed have the same issue using `"`.

**Comment by kabouzeid** [comment]
But it does work with `'`?

**Comment by mickael-menu** [comment]
Yes, this is what I have:

```
Plug 'mickael-menu/zk-nvim'
```

Using `"`, the plugin is simply not visible with `:PlugInstall`.

**Comment by tomtomjhj** [comment]
`Plug` is [defined with `-bar` attribute](https://github.com/junegunn/vim-plug/blob/e300178a0e2fb04b56de8957281837f13ecf0b27/plug.vim#L266) ([`:command-bar`](https://vimhelp.org/map.txt.html#%3Acommand-bar)), so `"` is interpreted as a comment marker.
