### ISSUE TITLE
Jump to the next link with <TAB>

### ISSUE THREAD

**Issue by mickael-menu** [mickael-menu/zk-nvim#4]
One particular feature I like about Vimwiki is to jump to the next or previous link with `<(S-)Tab>`. This makes it very easy to browse a notebook.

Maybe it's something that could be added to `zk-nvim` as well.

**Comment by smithbm2316** [comment]
I'll try and add this with the PR that I'm hoping to open this weekend with the other API wrapper functions. I think this should be quite easy to do 😄

**Comment by mickael-menu** [comment]
That would be great, thanks!

**Comment by smithbm2316** [comment]
For those who want to accomplish this, here are two keymaps that will allow you to do so that you can put into your own personal config for when the `zk` LSP is attached to a buffer:

```lua
-- jump to the next link
vim.api.nvim_set_keymap('n', ']n', [[lua vim.diagnostic.goto_next { severity = vim.diagnostic.severity.HINT }<cr>]], { noremap = true, silent = true })

-- jump to the previous link
vim.api.nvim_set_keymap('n', '[n', [[lua vim.diagnostic.goto_prev { severity = vim.diagnostic.severity.HINT }<cr>]], { noremap = true, silent = true })
```
