### ISSUE TITLE
Telescope config ignored

### ISSUE THREAD

**Issue by mehalter** [mickael-menu/zk-nvim#43]
When I use the build in picker commands with `picker = "telescope"` it seems to ignore my telescope config. This is fixed when I use the telescope plugin. Is there a reason that the telescope plugin is not recommended/full featured? And is there a way to get the commands like `:ZkNotes`/`:ZkLinks`/etc. to respect my telescope config?

**Comment by kabouzeid** [comment]
What part of your telescope config is ignored? Could you provide a minimal example? :)

**Comment by mehalter** [comment]
After some debugging  I realized what was happening 😂 sorry! My lazy loading of telescope was getting in the way! This is working correctly now that I have fixed that. I will go ahead and close this out
