### ISSUE TITLE
`$ZK_NOTEBOOK_DIR` not works

### ISSUE THREAD

**Issue by realVEct0r** [mickael-menu/zk-nvim#45]
I have configurated `$ZK_NOTEBOOK_DIR`, and `zk` command runs well, but it still cannot found notebook in neovim.

`~/.zshrc`:
```shell
export ZK_NOTEBOOK_DIR="$HOME/Notes"
```

```shell
 $  echo $ZK_NOTEBOOK_DIR
/Users/<username>/Notes

```

`zk` command:
```shell
 $  zk list
INDEX index.md (12 hours ago)

  ‣ Content goes here.


Found 1 note

```

plugin settings:
```lua
zk.setup {
    picker = 'telescope'
}
```

nvim `ZkNotes` command:
```
Error executing vim.schedule lua callback: ...cal/share/nvim/site/pack/packer/st
art/zk-nvim/lua/zk.lua:99: RPC[Error] code_name = InvalidRequest, message = "fai
led to open notebook: no notebook found in /Users/<username>/.config/nvim or a paren
t directory"
stack traceback:
        [C]: in function 'assert'
        ...cal/share/nvim/site/pack/packer/start/zk-nvim/lua/zk.lua:99: in funct
ion 'handler'
        ...l/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:964: in func
tion 'cb'
        vim.lua:285: in function <vim.lua:285>
Press ENTER or type command to continue
```

----
```shell
 $  zk --version
zk 0.9.0

 $  nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

**Comment by kabouzeid** [comment]
From within neovim, what is the output of `:echo $ZK_NOTEBOOK_DIR`?

**Comment by realVEct0r** [comment]
> From within neovim, what is the output of `:echo $ZK_NOTEBOOK_DIR`?

<img width="650" alt="image" src="https://user-images.githubusercontent.com/18254081/159836117-0f7ce922-7e19-4e25-aa5a-c01ba1aefdc5.png">

**Comment by kabouzeid** [comment]
but what if you run the `:echo $ZK_NOTEBOOK_DIR` vim command, not executing it in the builtin terminal.

**Comment by realVEct0r** [comment]
> but what if you run the `:echo $ZK_NOTEBOOK_DIR` vim command, not executing it in the builtin terminal.

sry for my misunderstand.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/18254081/159890558-fb349a0f-cf90-4cb3-bbe5-527be0425b9a.png">

I have tried to clone dotfiles to a new linux vm and found all of it works properly, so I guess maybe there is something unexpected when launch LSP server. but I have no experience about development and debug LSP server. I have tried to read source code related to this part of `zk` and have no ideas now.

**Comment by Dronakurl** [comment]
I have the same issue, $ZK_NOTEBOOK_DIR is ignored.

```
Error executing vim.schedule lua callback: /home/user/.local/share/nvim/lazy/zk-nvim/lua/zk.lua:103: RPC[Error] code_name = InvalidRequest, mes
sage = "failed to open notebook: no notebook found in XXXXXXXXXXPATHDELETEDXXXXXXXXX or a parent directory"                             
stack traceback:                                                                                                                                 
        [C]: in function 'assert'                                                                                                                
        /home/user/.local/share/nvim/lazy/zk-nvim/lua/zk.lua:103: in function 'handler'                                                        
        ...y/nvim-linux64/share/nvim/runtime/lua/vim/lsp/client.lua:662: in function ''                                                          
        vim/_editor.lua: in function <vim/_editor.lua:0>   
```
