### ISSUE TITLE
How can we input tags from the nvim commandline?

### ISSUE THREAD

**Issue by kabinspace** [mickael-menu/zk-nvim#46]
Since we can easily input our title from the nvim commandline like this:
```lua
n = { "<cmd>ZkNew { dir = vim.fn.expand('%:p:h'), title = vim.fn.input('Title: ') }<cr>", "New Notes" }
```
Is there a way we could have same input option for tags as well?
This is my `.zk/templates/default.md`
```handlebars
---
title: {{ title }}
date: {{ date now "long" }}
tags: {{ tags }}
---

{{content}}
```

**Comment by mickael-menu** [comment]
The `tags` template variable doesn't exist [when creating new notes](https://github.com/mickael-menu/zk/blob/main/docs/template-creation.md). However, you can use [a custom `extra` variable](https://github.com/mickael-menu/zk/blob/main/docs/config-extra.md) for this:

```md
---
title: {{ title }}
date: {{ date now "long" }}
tags: {{ extra.tags }}
---

{{content}}
```

Then you can use a similar method to set the extra variable with NeoVim:

```lua
n = { "<cmd>ZkNew { dir = vim.fn.expand('%:p:h'), title = vim.fn.input('Title: '), extra = { tags = vim.fn.input('Tags') }}<cr>", "New Notes" }
```

(Note that `extra` is a dictionary, I'm not sure the above syntax is correct actually, I didn't test it out myself).

**Comment by kabinspace** [comment]
Great, the given solution works perfectly fine. Thank you :)
