### ISSUE TITLE
Floaterm + ask for title

### ISSUE THREAD

**Issue by zeljkomarinkovic** [mickael-menu/zk-nvim#58]
Is it possible to chain commands in some manner so i get asked for title and open new note in floaterm?

What i tried is:
```vim
vim.api.nvim_set_keymap("n", "<leader>zt", "<Cmd>Floaterm ZkNew { title = vim.fn.input('Title: ') }<CR>", opts)
```
but this gets me this error 
<img width="401" alt="Screenshot 2022-06-23 at 00 24 15" src="https://user-images.githubusercontent.com/23746207/175163607-356f40b8-316c-4176-9a12-6b1e24f316f2.png">

**Comment by zeljkomarinkovic** [comment]
i know that that works, but i would like to have floating window where i can write down a thought, note, todo, whatever and hide it or close it and continue to work on project

**Comment by eric-hansen** [comment]
Not really sure this is going to work the way you want, but I could be wrong.

You're passing what is essentially a shell command to Floatterm, but ZkNew is not a shell command it's a Neovim command.

You could look at doing what I suggested and then opening up the file in a split buffer.  But you're trying to fit a round peg in a square hole atm.

**Comment by mickael-menu** [comment]
There's no out-of-the-box solution for this.

I think it would be possible to do basically this:

https://github.com/mickael-menu/zk-nvim/blob/614ec31800174e0f6dc1aeaa528eafb9de1193a5/lua/zk.lua#L65-L75

but replacing `vim.cmd("edit " .. res.path)` with the creation of [an nvim floating window buffer](https://neovim.io/doc/user/api.html).

Overall, it would be interesting to have more customization on how a note is opened (current window, new window, floating window, etc.).

**Comment by zeljkomarinkovic** [comment]
@eric-hansen 
I have also figured that out little bit too late 

@mickael-menu 
I will give it a go, if i come with some solution will make PR, thanks
