### ISSUE TITLE
Bug: completion window doesn't popup when there's non ascii character ahead

### ISSUE THREAD

**Issue by wrvsrx** [mickael-menu/zk-nvim#69]
# Description

In this post, I use `|` to represent cursor location.

When use zk-nvim, I found that if there is a non-ascii character in front of the cursor, then `[[` can't trigger completion.

For example, following content can trigger completion
 
```markdown
alpha [[|
```

But this one can't 

```markdown
α [[|
```

Here is a minimal working init.lua:

```lua
require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use 'neovim/nvim-lspconfig'

  use 'hrsh7th/nvim-cmp'
  use 'mickael-menu/zk-nvim'
end)

-- nvim-cmp
require'cmp'.setup {
  sources = cmp.config.sources({
    { name = 'nvim_lsp' },
  })
}

-- zk
require("zk").setup{}
```

# Reproduce

1. Create a zk folder with an aribitary note
2. Create a note with `zk new`
3. Edit the new note by `nvim <note name> -u init.lua` (assume packer.nvim and these plugins have been installed)
4. Input `alpha [[`, you'll notice that completion windows popup
5. Start a new line and input `α [[`, nothing happens here.

`α` can be changed to any non-ascii character, such as `你好`.

**Comment by aleksey-rowan** [comment]
@wrvsrx, does the minimal config still works for you?

I get an error on `sources = cmp.config.sources({`:
```
E5113: Error while calling lua chunk: ~/.config/nvim/init.lua:13: attempt to index field 'config' (a nil value)
```

If I change it to `sources = { { name = 'nvim_lsp' } }`, the error goes away, but the autocompletion on `[[` still doesn't work.

**Comment by wrvsrx** [comment]
@aleksey-rowan My minimal configuration file may be outdated due to updates of nvim-cmp. Would you mind providing a working config file? I have recently switched to coc.nvim, but this bug persists.

**Comment by aleksey-rowan** [comment]
> Would you mind providing a working config file? I have recently switched to coc.nvim, but this bug persists.

@wrvsrx, that's the problem--I couldn't figure out how to get autocompletion working with built-in LSP in the first place and then saw you had a minimal config that was supposed to work. Sorry, I don't want to get this issue off topic.
