### ISSUE TITLE
Telescope Error when scrolling 

### ISSUE THREAD

**Issue by thecontinium** [mickael-menu/zk-nvim#76]
When I use ZkNotes and scroll down and then back up I get this error. 

``` vim
Error executing vim.schedule lua callback: .../telescope.nvim_0.1.x/lua/telescope/previewers/utils.lua:158: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_get_height'
        .../telescope.nvim_0.1.x/lua/telescope/previewers/utils.lua:158: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue

```

Going back up one at a time ie slowly does not produce the error. 
Holding down the up key and stopping produces many of these errors.
I can't repeat this in any another Telescope "action" which is why I am raising it here.

Does anyone else experience this ?

**Comment by thecontinium** [comment]
I have j,k mapped to up/down for telegram. This problem occurred when I added additional mapping starting with j or k.

**Comment by mickael-menu** [comment]
This error occurs in [`telescope.nvim`](https://github.com/nvim-telescope/telescope.nvim), are you sure it's related to `zk-nvim`?

**Comment by thecontinium** [comment]
It’s a telescope problem.
