### ISSUE TITLE
Is neorg support planned

### ISSUE THREAD

**Issue by sp4ke** [mickael-menu/zk-nvim#78]
Hi, 

Thanks for your work on this plugin.

Are there any plans to support [neorg](https://github.com/nvim-neorg/neorg) ? 

This would be a perfect match for zk.

**Comment by mickael-menu** [comment]
Are you talking about supporting org mode files? It's not planned but there's this relevant issue: https://github.com/mickael-menu/zk/issues/143

**Comment by sp4ke** [comment]
No I meant [neorg](https://github.com/nvim-neorg/neorg) with the `norg`  file format. There is a change this will become the standard org equivalent for neovim if not better and zk would be a perfect plugin for neorg.

**Comment by sp4ke** [comment]
No I meant the norg file format from neorg 
see https://github.com/nvim-neorg/neorg

I use zk but neorg has much more potential and as the base file format for all the community that will build around it.

**Comment by mickael-menu** [comment]
I see, it's not something I'm personally interested in working on. But see the discussion in this issue if you want to tackle the implementation: https://github.com/mickael-menu/zk/issues/143

**Comment by sp4ke** [comment]
Ok thanks 👍
