### ISSUE TITLE
Feature request: apply template to already created note

### ISSUE THREAD

**Issue by zmre** [mickael-menu/zk-nvim#91]
Request: 

A command to apply a template to the current file.

Background:

I keep tasks in my notes in github markdown format. Sometimes I want to kick a task to the future and for that, I move the task to a journal note with a future date.  When that date arrives, I don't have my nice journal template in it. I have to copy out the contents, delete the file, then have zk recreate it and finally paste back in the contents. Needless to say, this is not ideal.

This would also be useful for me as I'd like to create some templates for things like reviews of books. I realize I can read in the template, but I do like to have the substitutions work. So if I even just had a way to ask zk to replace template values, that would be a big step forward.

If there's already a way to do this, I couldn't find it after poring over the docs, but would love to know the secret.

Thanks for this tool, it's great!

**Comment by mickael-menu** [comment]
So if I understand correctly, you want to create a new note from a `zk` template, but instead of writing the note to the file system, you want to insert its content at the caret position in Vim?

**Comment by zmre** [comment]
Yes, that would work to accomplish my needs. Is there a way to do that?

**Comment by mickael-menu** [comment]
Yes but you will need to update `zk-nvim` and build+install `zk` from the latest `develop` state, as I merged this feature two days ago.

Then, you can add the `inline = true` option to any `ZkNew*` command, e.g. `:ZkNewFromSelection { inline = true, template = "book-review.md" }`.

**Comment by zmre** [comment]
Brilliant, thank you!
